export const EDITOR_HISTORY_DEPTH = 100;
export const EDITOR_HISTORY_GROUP_DELAY_MS = 1_000;
export const EDITOR_HISTORY_NOTE_CACHE_LIMIT = 50;

export const EDITOR_HISTORY_CONFIG = {
  depth: EDITOR_HISTORY_DEPTH,
  newGroupDelay: EDITOR_HISTORY_GROUP_DELAY_MS,
};
